"""
PDF Report Generator for Grain Size Analysis
Creates comprehensive analysis reports with histograms, tables, and images.
"""

import os
import numpy as np
import pandas as pd
from datetime import datetime
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Rectangle
import cv2


class PDFReportGenerator:
    """Generate comprehensive PDF reports for grain analysis."""
    
    def __init__(self, output_dir, base_name):
        """
        Initialize PDF report generator.
        
        Args:
            output_dir: Directory for output files
            base_name: Base name for the report
        """
        self.output_dir = output_dir
        self.base_name = base_name
        self.report_path = os.path.join(output_dir, f"{base_name}_ANALYSIS_REPORT.pdf")
        
    def create_complete_report(self, variant_results, combined_results, 
                               processing_config, metadata, overlay_paths=None,
                               exported_files=None):
        """
        Create a complete PDF report with all analysis results.
        
        Args:
            variant_results: List of variant result dictionaries
            combined_results: Combined analysis results
            processing_config: Processing configuration dictionary
            metadata: Analysis metadata (image path, dimensions, etc.)
            overlay_paths: Dictionary of {variant_name: overlay_image_path}
            exported_files: Dictionary of exported file paths (CSV files)
        """
        with PdfPages(self.report_path) as pdf:
            # Page 1: Title and Summary
            self._create_title_page(pdf, metadata, combined_results)
            
            # Page 2: Combined Histograms
            self._create_combined_histograms(pdf, variant_results)
            
            # Page 3: Per-Profile Statistics Table
            self._create_profile_statistics_table(pdf, variant_results)
            
            # Page 4: Excel/CSV Data Tables
            if exported_files:
                self._create_csv_data_pages(pdf, exported_files)
            
            # Page 5+: Grain Images for Each Profile
            if overlay_paths:
                self._create_grain_image_pages(pdf, variant_results, overlay_paths)
            
            # Add metadata
            d = pdf.infodict()
            d['Title'] = f'Grain Size Analysis Report - {self.base_name}'
            d['Author'] = 'Grain Size Calculator'
            d['Subject'] = 'SEM Grain Analysis'
            d['CreationDate'] = datetime.now()
            
        return self.report_path
    
    def _create_title_page(self, pdf, metadata, combined_results):
        """Create title page with summary information."""
        fig = plt.figure(figsize=(8.5, 11))
        fig.patch.set_facecolor('white')
        
        # Title
        plt.text(0.5, 0.85, 'GRAIN SIZE ANALYSIS REPORT', 
                ha='center', va='top', fontsize=24, fontweight='bold')
        
        # Separator line
        plt.plot([0.1, 0.9], [0.80, 0.80], 'k-', linewidth=2)
        
        # Sample information
        y_pos = 0.72
        line_spacing = 0.05
        
        info_items = [
            ('Sample:', self.base_name),
            ('Analysis Date:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')),
            ('Image Dimensions:', f"{metadata.get('image_dimensions', ('?', '?'))[0]} × {metadata.get('image_dimensions', ('?', '?'))[1]} pixels"),
            ('Pixel Scale:', f"{metadata.get('um_per_pixel', 0):.4f} µm/pixel"),
            ('Frame Width:', f"{metadata.get('frame_width_um', 0):.2f} µm"),
            ('', ''),
            ('SUMMARY STATISTICS', ''),
            ('Total Profiles Analyzed:', str(metadata.get('total_variants', 0))),
            ('Total Grains Detected:', str(combined_results.get('total_grains_pooled', 0))),
            ('', ''),
            ('Overall Average Chord Length:', f"{combined_results.get('overall_chord_statistics').mean:.3f} µm"),
            ('Overall Average Area:', f"{combined_results.get('overall_area_statistics').mean:.3f} µm²"),
        ]
        
        for label, value in info_items:
            if label == 'SUMMARY STATISTICS':
                plt.text(0.5, y_pos, label, ha='center', va='top', 
                        fontsize=14, fontweight='bold')
            elif label:
                plt.text(0.15, y_pos, label, ha='left', va='top', 
                        fontsize=11, fontweight='bold')
                plt.text(0.55, y_pos, str(value), ha='left', va='top', fontsize=11)
            y_pos -= line_spacing
        
        # Footer
        plt.text(0.5, 0.05, 'Generated by Grain Size Calculator - SAM-B Model with Experimental Profiles',
                ha='center', va='bottom', fontsize=9, style='italic', color='gray')
        
        plt.xlim(0, 1)
        plt.ylim(0, 1)
        plt.axis('off')
        
        pdf.savefig(fig, bbox_inches='tight')
        plt.close()
    
    def _create_combined_histograms(self, pdf, variant_results):
        """Create page with combined histograms for chord and area."""
        fig = plt.figure(figsize=(8.5, 11))
        fig.suptitle('Combined Distribution Histograms', fontsize=16, fontweight='bold', y=0.98)
        
        # Collect all measurements across variants
        all_chords = []
        all_areas = []
        
        for result in variant_results:
            if result.get('grains_used', 0) > 0:
                all_chords.extend(result.get('raw_chords_um', []))
                all_areas.extend(result.get('raw_areas_um2', []))
        
        if not all_chords:
            plt.text(0.5, 0.5, 'No grain data available', 
                    ha='center', va='center', fontsize=14)
            plt.axis('off')
            pdf.savefig(fig, bbox_inches='tight')
            plt.close()
            return
        
        # Create 3 subplots
        gs = gridspec.GridSpec(3, 1, height_ratios=[1, 1, 1], hspace=0.4)
        
        # Histogram 1: Chord Length Distribution
        ax1 = fig.add_subplot(gs[0])
        n, bins, patches = ax1.hist(all_chords, bins=30, color='steelblue', 
                                     edgecolor='black', alpha=0.7)
        ax1.set_xlabel('Chord Length (µm)', fontsize=11, fontweight='bold')
        ax1.set_ylabel('Frequency', fontsize=11, fontweight='bold')
        ax1.set_title(f'Chord Length Distribution (n={len(all_chords)} grains)', 
                     fontsize=12, fontweight='bold')
        ax1.grid(True, alpha=0.3)
        
        # Add statistics text
        mean_chord = np.mean(all_chords)
        
        stats_text = f'Mean: {mean_chord:.3f} µm'
        ax1.text(0.97, 0.97, stats_text, transform=ax1.transAxes,
                fontsize=10, verticalalignment='top', horizontalalignment='right',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))
        
        # Histogram 2: Area Distribution
        ax2 = fig.add_subplot(gs[1])
        n, bins, patches = ax2.hist(all_areas, bins=30, color='coral', 
                                     edgecolor='black', alpha=0.7)
        ax2.set_xlabel('Grain Area (µm²)', fontsize=11, fontweight='bold')
        ax2.set_ylabel('Frequency', fontsize=11, fontweight='bold')
        ax2.set_title(f'Area Distribution (n={len(all_areas)} grains)', 
                     fontsize=12, fontweight='bold')
        ax2.grid(True, alpha=0.3)
        
        # Add statistics text
        mean_area = np.mean(all_areas)
        
        stats_text = f'Mean: {mean_area:.3f} µm²'
        ax2.text(0.97, 0.97, stats_text, transform=ax2.transAxes,
                fontsize=10, verticalalignment='top', horizontalalignment='right',
                bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.8))
        
        # Histogram 3: Per-Profile Min/Max Comparison
        ax3 = fig.add_subplot(gs[2])
        
        profile_names = []
        min_grains = []
        max_grains = []
        
        for result in variant_results:
            if result.get('grains_used', 0) > 0:
                chords = result.get('raw_chords_um', [])
                if chords:
                    name = result.get('variant_name', 'Unknown')
                    # Truncate long names
                    if len(name) > 25:
                        name = name[:22] + '...'
                    profile_names.append(name)
                    min_grains.append(np.min(chords))
                    max_grains.append(np.max(chords))
        
        if profile_names:
            x = np.arange(len(profile_names))
            width = 0.35
            
            bars1 = ax3.bar(x - width/2, min_grains, width, label='Min Grain', 
                           color='lightgreen', edgecolor='black', alpha=0.8)
            bars2 = ax3.bar(x + width/2, max_grains, width, label='Max Grain', 
                           color='salmon', edgecolor='black', alpha=0.8)
            
            ax3.set_xlabel('Profile', fontsize=11, fontweight='bold')
            ax3.set_ylabel('Chord Length (µm)', fontsize=11, fontweight='bold')
            ax3.set_title('Min/Max Grain Size per Profile', fontsize=12, fontweight='bold')
            ax3.set_xticks(x)
            ax3.set_xticklabels(profile_names, rotation=45, ha='right', fontsize=8)
            ax3.legend(fontsize=9)
            ax3.grid(True, alpha=0.3, axis='y')
            
            # Add value labels on bars
            for bar in bars1:
                height = bar.get_height()
                ax3.text(bar.get_x() + bar.get_width()/2., height,
                        f'{height:.2f}', ha='center', va='bottom', fontsize=7)
            for bar in bars2:
                height = bar.get_height()
                ax3.text(bar.get_x() + bar.get_width()/2., height,
                        f'{height:.2f}', ha='center', va='bottom', fontsize=7)
        
        pdf.savefig(fig, bbox_inches='tight')
        plt.close()
    
    def _create_profile_statistics_table(self, pdf, variant_results):
        """Create page with per-profile statistics table."""
        fig = plt.figure(figsize=(8.5, 11))
        fig.suptitle('Per-Profile Statistics Summary', fontsize=16, fontweight='bold', y=0.98)
        
        # Prepare data for table
        table_data = []
        headers = ['Profile Name', 'Grains', 'Avg Chord\n(µm)', 'Std Dev\n(µm)', 
                  'Min Chord\n(µm)', 'Max Chord\n(µm)', 'Avg Area\n(µm²)']
        
        for result in variant_results:
            profile_name = result.get('variant_name', 'Unknown')
            grains_used = result.get('grains_used', 0)
            
            if grains_used > 0:
                chords = result.get('raw_chords_um', [])
                areas = result.get('raw_areas_um2', [])
                
                avg_chord = np.mean(chords) if chords else 0
                std_chord = np.std(chords) if chords else 0
                min_chord = np.min(chords) if chords else 0
                max_chord = np.max(chords) if chords else 0
                avg_area = np.mean(areas) if areas else 0
                
                # Truncate long profile names
                display_name = profile_name if len(profile_name) <= 35 else profile_name[:32] + '...'
                
                table_data.append([
                    display_name,
                    str(grains_used),
                    f'{avg_chord:.3f}',
                    f'{std_chord:.3f}',
                    f'{min_chord:.3f}',
                    f'{max_chord:.3f}',
                    f'{avg_area:.3f}'
                ])
        
        if not table_data:
            plt.text(0.5, 0.5, 'No profile data available', 
                    ha='center', va='center', fontsize=14)
            plt.axis('off')
            pdf.savefig(fig, bbox_inches='tight')
            plt.close()
            return
        
        # Create table
        ax = fig.add_subplot(111)
        ax.axis('off')
        
        table = ax.table(cellText=table_data, colLabels=headers,
                        loc='center', cellLoc='center')
        
        table.auto_set_font_size(False)
        table.set_fontsize(9)
        table.scale(1, 2.5)
        
        # Style header row
        for i in range(len(headers)):
            cell = table[(0, i)]
            cell.set_facecolor('#4CAF50')
            cell.set_text_props(weight='bold', color='white')
        
        # Alternate row colors
        for i in range(1, len(table_data) + 1):
            for j in range(len(headers)):
                cell = table[(i, j)]
                if i % 2 == 0:
                    cell.set_facecolor('#f0f0f0')
                else:
                    cell.set_facecolor('white')
        
        pdf.savefig(fig, bbox_inches='tight')
        plt.close()
    
    def _create_grain_image_pages(self, pdf, variant_results, overlay_paths):
        """Create pages showing grain detection images for each profile."""
        for result in variant_results:
            variant_name = result.get('variant_name', 'Unknown')
            grains_used = result.get('grains_used', 0)
            
            if variant_name not in overlay_paths:
                continue
            
            overlay_path = overlay_paths[variant_name]
            if not os.path.exists(overlay_path):
                continue
            
            # Load overlay image
            try:
                img = cv2.imread(overlay_path)
                if img is None:
                    continue
                img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            except Exception as e:
                print(f"Error loading overlay for {variant_name}: {e}")
                continue
            
            # Create figure
            fig = plt.figure(figsize=(8.5, 11))
            
            # Title with profile name and grain count
            display_name = variant_name if len(variant_name) <= 50 else variant_name[:47] + '...'
            fig.suptitle(f'{display_name}\n{grains_used} Grains Detected', 
                        fontsize=14, fontweight='bold', y=0.98)
            
            # Show image
            ax = fig.add_subplot(111)
            ax.imshow(img_rgb)
            ax.axis('off')
            
            # Add statistics box
            chords = result.get('raw_chords_um', [])
            if chords:
                stats_text = (f'Avg Chord: {np.mean(chords):.3f} µm\n'
                            f'Std Dev: {np.std(chords):.3f} µm\n'
                            f'Min: {np.min(chords):.3f} µm\n'
                            f'Max: {np.max(chords):.3f} µm')
                
                ax.text(0.02, 0.98, stats_text, transform=ax.transAxes,
                       fontsize=10, verticalalignment='top',
                       bbox=dict(boxstyle='round', facecolor='white', alpha=0.9))
            
            pdf.savefig(fig, bbox_inches='tight', dpi=150)
            plt.close()
    
    def _create_csv_data_pages(self, pdf, exported_files):
        """Create pages showing CSV data tables."""
        if not exported_files:
            print("Warning: No exported files provided for CSV data pages")
            return
        
        # Define which files to include in PDF (overall_summary shown on title page)
        file_keys = ['chord_summary', 'area_summary']
        file_titles = {
            'chord_summary': 'Per-Variant Chord Length Summary',
            'area_summary': 'Per-Variant Area Summary'
        }
        
        print(f"Creating CSV pages, exported_files keys: {list(exported_files.keys())}")
        
        for file_key in file_keys:
            if file_key not in exported_files:
                print(f"Warning: {file_key} not in exported_files")
                continue
            
            csv_path = exported_files[file_key]
            print(f"Processing {file_key}: {csv_path}")
            
            if not os.path.exists(csv_path):
                print(f"Warning: CSV file does not exist: {csv_path}")
                continue
            
            try:
                # Read CSV file
                df = pd.read_csv(csv_path)
                
                # Create figure
                fig = plt.figure(figsize=(8.5, 11))
                fig.suptitle(file_titles.get(file_key, 'Data Table'), 
                           fontsize=16, fontweight='bold', y=0.98)
                
                ax = fig.add_subplot(111)
                ax.axis('off')
                
                # Convert dataframe to table format
                table_data = df.values.tolist()
                col_labels = df.columns.tolist()
                
                # Truncate long values for display
                for i, row in enumerate(table_data):
                    for j, val in enumerate(row):
                        if isinstance(val, str) and len(val) > 30:
                            table_data[i][j] = val[:27] + '...'
                        elif isinstance(val, float):
                            table_data[i][j] = f'{val:.4f}'
                
                # Create table
                table = ax.table(cellText=table_data, colLabels=col_labels,
                               loc='center', cellLoc='center')
                
                table.auto_set_font_size(False)
                table.set_fontsize(8)
                table.scale(1, 2)
                
                # Style header row
                for i in range(len(col_labels)):
                    cell = table[(0, i)]
                    cell.set_facecolor('#2196F3')
                    cell.set_text_props(weight='bold', color='white')
                
                # Alternate row colors
                for i in range(1, len(table_data) + 1):
                    for j in range(len(col_labels)):
                        cell = table[(i, j)]
                        if i % 2 == 0:
                            cell.set_facecolor('#f5f5f5')
                        else:
                            cell.set_facecolor('white')
                
                # Add file path note
                plt.text(0.5, 0.02, f'Data exported to: {os.path.basename(csv_path)}',
                        ha='center', fontsize=8, style='italic', color='gray',
                        transform=fig.transFigure)
                
                pdf.savefig(fig, bbox_inches='tight')
                plt.close()
                print(f"Successfully added {file_key} to PDF")
                
            except Exception as e:
                print(f"Error creating table for {file_key}: {e}")
                import traceback
                traceback.print_exc()
                continue


def create_pdf_report_generator(output_dir, base_name):
    """
    Factory function to create PDF report generator.
    
    Args:
        output_dir: Directory for output files
        base_name: Base name for the report
        
    Returns:
        PDFReportGenerator instance
    """
    return PDFReportGenerator(output_dir, base_name)
